[general]

import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 10.0

[font.normal]
family = "SauceCodePro NerdFont"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[mouse]
hide_when_typing = true


